name: Fetch TMDb Top Rated + Streaming Availability

on:
  schedule:
    - cron: '0 4 1 * *'      # monthly at 4 AM UTC on the 1st
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Fetch top-rated movies (pages 1–40)
        run: |
          mkdir -p data
          for page in {1..40}; do
            curl -s "https://api.themoviedb.org/3/movie/top_rated?api_key=${{ secrets.TMDB_API_KEY }}&language=en-US&page=$page" \
              | jq '.results' > data/page${page}.json
          done

      - name: Combine into single list
        run: |
          jq -s 'flatten' data/page*.json > data/all_movies.json

      - name: Enrich with TMDb watch providers & link
        run: |
          jq -c '.[]' data/all_movies.json | \
          while read -r movie; do
            id=$(jq -r '.id' <<<"$movie")
            raw=$(curl -s "https://api.themoviedb.org/3/movie/${id}/watch/providers?api_key=${{ secrets.TMDB_API_KEY }}")
            link=$(jq -r '.results.US.link // empty' <<<"$raw")
            wp=$(jq -c '
              [ .results.US.flatrate?[]?,
                .results.US.adSupported?[]? ]
              | flatten
              | unique_by(.provider_id)
            ' <<<"$raw")
            if [[ $(jq 'length' <<<"$wp") -gt 0 ]]; then
              echo "$movie" \
                | jq --arg link "$link" --argjson wp "$wp" \
                     '. + { watch_link: $link, watch_providers: $wp }'
            fi
          done | jq -s '.' > data/movies.json

      - name: Split into records needing (re)enrichment
        run: |
          mkdir -p data/records
          # only enrich those missing streaming_info or older than 30 days
          jq -c --arg today "$(date -u +%Y-%m-%d)" --argjson window $((30*86400)) '
            map(
              select(
                (.streaming_info == null)
                or
                (
                  (.last_checked? | strptime("%Y-%m-%d")? | mktime)
                  <
                  ($today | strptime("%Y-%m-%d") | mktime) - $window
                )
              )
            )[]
          ' data/movies.json \
          | split -l 1 - data/records/movie_

      - name: Enrich with RapidAPI streaming-availability
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        run: |
          rm -f data/new_enriched.json
          for f in data/records/movie_*; do
            movie=$(cat "$f")
            id=$(jq -r '.id' <<<"$movie")
            resp=$(curl -s \
              -H "X-RapidAPI-Key: $RAPIDAPI_KEY" \
              -H "X-RapidAPI-Host: streaming-availability.p.rapidapi.com" \
              "https://streaming-availability.p.rapidapi.com/get/basic?tmdb_id=$id&country=all")
            results=$(jq '.results' <<<"$resp")
            echo "$movie" \
              | jq --argjson si "$results" --arg today "$(date -u +%Y-%m-%d)" \
                   '. + { streaming_info: $si, last_checked: $today }' \
              >> data/new_enriched.json
            sleep 0.2
          done

      - name: Finalize movies.json (merge & cap at 800)
        run: |
          jq -s '
            # flatten both arrays, keep only objects, dedupe, then slice
            [ .[0][] , .[1][] ]
            | map(select(type=="object"))
            | unique_by(.id)
            | .[0:5]
          ' data/movies.json data/new_enriched.json > data/movies.json

      - name: Commit updated movies.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/movies.json
          git commit -m "chore: update TMDb cache + streaming availability" || echo "No changes"
          git push
