name: Fetch TMDb Top Rated

# Grant write access so the GITHUB_TOKEN can push commits
permissions:
  contents: write

on:
  schedule:
    - cron: '0 4 * * *'      # daily at 4 AM UTC
  workflow_dispatch: {}      # allows manual runs

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Fetch top-rated movies (pages 1–40)
        run: |
          mkdir -p data
          for page in {1..40}; do
            curl -s "https://api.themoviedb.org/3/movie/top_rated?api_key=${{ secrets.TMDB_API_KEY }}&language=en-US&page=$page" \
              | jq '.results' > data/page${page}.json
          done

      - name: Combine into single list
        run: |
          jq -s 'flatten' data/page*.json > data/all_movies.json

      - name: Enrich with watch providers & filter
        run: |
          jq -c '.[]' data/all_movies.json | \
          while read -r movie; do
            id=$(jq -r '.id' <<<"$movie")
            # Fetch raw watch providers JSON
            raw=$(curl -s "https://api.themoviedb.org/3/movie/${id}/watch/providers?api_key=${{ secrets.TMDB_API_KEY }}")
            # Extract the watch-link (TMDb page for where to watch)
            link=$(jq -r '.results.US.link // empty' <<<"$raw")
            # Gather all provider objects (flatrate / adSupported / rent / buy), dedupe by provider_id
            providers=$(jq -c '
              [ .results.US.flatrate?[]?,
                .results.US.adSupported?[]?,
                .results.US.rent?[]?,
                .results.US.buy?[]? ]
              | flatten
              | unique_by(.provider_id)
            ' <<<"$raw")
            # Only include if at least one provider
            if [[ $(jq 'length' <<<"$providers") -gt 0 ]]; then
              # Merge watch_link and watch_providers into the movie object
              echo "$movie" \
                | jq --arg link "$link" --argjson wp "$providers" \
                     '. + { watch_link: $link, watch_providers: $wp }'
            fi
          done | jq -s '.' > data/movies.json

      - name: Slice to first 800 (optional cap)
        run: |
          jq '.[0:800]' data/movies.json > data/movies.json.tmp
          mv data/movies.json.tmp data/movies.json

      - name: Commit updated movies.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/movies.json
          git commit -m "chore: update TMDb cache with full watch providers data" || echo "No changes"
          git push
