name: Fetch TMDb Top Rated

permissions:
  contents: write

on:
  schedule:
    - cron: '0 4 * * *'      # daily at 4 AM UTC
  workflow_dispatch: {}

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Fetch top-rated movies (pages 1–40)
        run: |
          mkdir -p data
          for page in {1..40}; do
            curl -s "https://api.themoviedb.org/3/movie/top_rated?api_key=${{ secrets.TMDB_API_KEY }}&language=en-US&page=$page" \
              | jq '.results' > data/page${page}.json
          done

      - name: Combine into a single raw list
        run: |
          jq -s 'flatten' data/page*.json > data/all_movies.json

      # === THE NEW, SIMPLIFIED LOGIC ===
      # No more complex filtering. We take the raw list and process it.

      - name: Slice to a max of 800 movies and create movies.json
        run: |
          # This step now takes the raw list and creates our main movies.json file.
          jq '.[0:800]' data/all_movies.json > data/movies.json

      - name: Prune to only necessary fields for fast loading
        run: |
          # We add a generic watch_link to every movie.
          jq '[.[] | . + {watch_link: ("https://www.themoviedb.org/movie/" + (.id|tostring) + "/watch")}]' data/movies.json > data/movies.json.tmp
          
          # Then we keep only the fields the website needs.
          jq '[.[] | {id, title, release_date, poster_path, genre_ids, watch_link}]' data/movies.json.tmp > data/movies.json

      - name: Create daily pool of 10 random movies using shuf
        run: |
          jq -c '.[]' data/movies.json | shuf | head -n 10 | jq -s '.' > data/daily-pool.json

      - name: Commit updated movie files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/movies.json data/daily-pool.json
          git commit -m "chore: update TMDb movie caches" || echo "No changes"
          git push
