name: Fetch TMDb Top Rated

permissions:
  contents: write

on:
  schedule:
    - cron: '0 4 * * *'      # daily at 4 AM UTC
  workflow_dispatch: {}

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      # <<< MODIFIED: Updated to the latest version for best practice
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Fetch and process movies
        run: |
          mkdir -p data
          # Fetch all movies and combine them into a single temporary file
          jq -n '[]' > temp_all_movies.json
          for page in {1..40}; do
            curl -s "https://api.themoviedb.org/3/movie/top_rated?api_key=${{ secrets.TMDB_API_KEY }}&language=en-US&page=$page" \
              | jq '.results' >> temp_all_movies.json
          done
          
          # This command is already excellent. It correctly filters out movies without posters.
          jq -s 'flatten | map(select(.poster_path != null)) | .[0:800] | [.[] | . + {watch_link: ("https://www.themoviedb.org/movie/" + (.id|tostring) + "/watch")}] | [.[] | {id, title, release_date, poster_path, genre_ids, watch_link}]' temp_all_movies.json > data/movies.json

      # <<< REMOVED: The entire step for creating 'initial-pool.js' is gone.
      # This block has been deleted as it is no longer needed.

      - name: Commit updated movie files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # <<< MODIFIED: Only adds the single, essential movies.json file
          git add data/movies.json
          git commit -m "chore(data): update TMDb movie cache" || echo "No changes"
          git push
