name: Fetch TMDb Top Rated

permissions:
  contents: write

on:
  schedule:
    - cron: '0 4 * * *'      # daily at 4 AM UTC
  workflow_dispatch: {}

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Fetch and process movies
        run: |
          mkdir -p data
          # Fetch all movies
          jq -n '[]' > data/all_movies_filtered.json
          for page in {1..40}; do
            raw_page=$(curl -s "https://api.themoviedb.org/3/movie/top_rated?api_key=${{ secrets.TMDB_API_KEY }}&language=en-US&page=$page")
            
            # Use jq to process each movie in the page
            echo "$raw_page" | jq -c '.results[]' | while read -r movie; do
              # Add a generic watch_link to every movie
              echo "$movie" | jq '. + {watch_link: ("https://www.themoviedb.org/movie/" + (.id|tostring) + "/watch")}'
            done | jq -s '.' >> temp_page.json
          done
          
          # Combine all pages and prune to necessary fields
          jq -s 'flatten | .[0:800] | [.[] | {id, title, release_date, poster_path, genre_ids, watch_link}]' temp_page.json > data/movies.json
          
      # === THIS IS THE NEW, BULLETPROOF STEP ===
      - name: Create instant-load JS pool file
        run: |
          # Take 10 random movies from the main list
          daily_pool_json=$(jq 'shuffle | .[0:10]' data/movies.json)
          # Create a JavaScript file that assigns this data to a variable
          echo "const initialMoviePool = ${daily_pool_json};" > data/initial-pool.js

      - name: Commit updated movie files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # We now commit the main list and the new JS file
          git add data/movies.json data/initial-pool.js
          git commit -m "chore: update TMDb movie caches" || echo "No changes"
          git push
