name: Fetch TMDb Top Rated

# Grant write access so the GITHUB_TOKEN can push commits
permissions:
  contents: write

on:
  schedule:
    - cron: '0 4 * * *'      # daily at 4 AM UTC
  workflow_dispatch: {}      # allows manual runs

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Fetch top-rated movies (pages 1–40)
        run: |
          mkdir -p data
          for page in {1..40}; do
            curl -s "https://api.themoviedb.org/3/movie/top_rated?api_key=${{ secrets.TMDB_API_KEY }}&language=en-US&page=$page" \
              | jq '.results' > data/page${page}.json
          done

      - name: Combine into single list
        run: |
          jq -s 'flatten' data/page*.json > data/all_movies.json

      - name: Enrich with watch providers & filter
        run: |
          jq -c '.[]' data/all_movies.json | \
          while read -r movie; do
            id=$(jq -r '.id' <<<"$movie")
            # Fetch US watch providers and pick out only the numeric provider_id
            wp=$(curl -s "https://api.themoviedb.org/3/movie/${id}/watch/providers?api_key=${{ secrets.TMDB_API_KEY }}" \
                 | jq '[.results.US.flatrate?[]?.provider_id,
                        .results.US.adSupported?[]?.provider_id,
                        .results.US.rent?[]?.provider_id,
                        .results.US.buy?[]?.provider_id]
                       | flatten | unique')
            # Only include if non-empty
            if [[ $(jq 'length' <<<"$wp") -gt 0 ]]; then
              # Merge in watch_providers as a plain-number array
              echo "$movie" | jq --argjson wp "$wp" '. + {watch_providers: $wp}'
            fi
          done | jq -s '.' > data/movies.json

      - name: Slice to first 800 (if you still want to cap)
        run: |
          jq '.[0:800]' data/movies.json > data/movies.json.tmp
          mv data/movies.json.tmp data/movies.json

      - name: Commit updated movies.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/movies.json
          git commit -m "chore: update TMDb cache with watch providers" || echo "No changes"
          git push
