name: Fetch TMDb Top Rated

permissions:
  contents: write

on:
  schedule:
    - cron: '0 4 * * *'      # daily at 4 AM UTC
  workflow_dispatch: {}

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # === THIS IS THE CORRECTED DEPENDENCY INSTALLATION ===
      - name: Install curl
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Install latest version of jq
        uses: dcarbone/install-jq-action@v2.1.0
      # === END OF CORRECTION ===

      - name: Fetch top-rated movies (pages 1–40)
        run: |
          mkdir -p data
          for page in {1..40}; do
            curl -s "https://api.themoviedb.org/3/movie/top_rated?api_key=${{ secrets.TMDB_API_KEY }}&language=en-US&page=$page" \
              | jq '.results' > data/page${page}.json
          done

      - name: Combine into single list
        run: |
          jq -s 'flatten' data/page*.json > data/all_movies.json

      - name: Enrich and filter for streamable movies
        run: |
          jq -c '.[]' data/all_movies.json | \
          while read -r movie; do
            id=$(jq -r '.id' <<<"$movie")
            raw=$(curl -s "https://api.themoviedb.org/3/movie/${id}/watch/providers?api_key=${{ secrets.TMDB_API_KEY }}")
            link=$(jq -r '.results.US.link // empty' <<<"$raw")
            providers=$(jq -c '[ .results.US.flatrate?[], .results.US.free?[], .results.US.adSupported?[] ] | flatten')
            if [[ $(jq 'length' <<<"$providers") -gt 0 ]]; then
              echo "$movie" | jq --arg link "$link" '. + { watch_link: $link }'
            fi
          done | jq -s '.' > data/movies.json

      - name: Slice to a max of 800 movies
        run: |
          jq '.[0:800]' data/movies.json > data/movies.json.tmp
          mv data/movies.json.tmp data/movies.json

      - name: Prune to only necessary fields
        run: |
          jq '[.[] | {id, title, release_date, poster_path, genre_ids, watch_link}]' data/movies.json > data/movies.json.tmp
          mv data/movies.json.tmp data/movies.json

      - name: Create daily pool of 10 random movies
        run: |
          jq 'shuffle | .[0:10]' data/movies.json > data/daily-pool.json

      - name: Commit updated movie files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/movies.json data/daily-pool.json
          git commit -m "chore: update TMDb movie caches" || echo "No changes"
          git push
